# Generated by Django 5.1.2 on 2025-11-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDeliberationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=64, unique=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed session description')),
                ('objective_questions', models.JSONField(blank=True, default=list)),
                ('personas', models.JSONField(blank=True, default=list)),
                ('system_prompt_template', models.TextField(blank=True, help_text='System prompt template (placeholders: {persona}, {question}, {opinions})')),
                ('user_instructions', models.TextField(blank=True, help_text='Optional moderator-provided instructions for AI agents')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DiscussionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=64, unique=True)),
                ('objective_questions', models.JSONField(blank=True, default=list)),
                ('question_followup_limit', models.PositiveIntegerField(default=3)),
                ('no_new_information_limit', models.PositiveIntegerField(default=2)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description (rendered as markdown for users)')),
                ('user_system_prompt', models.TextField(blank=True, default="You are a well-informed reporter already familiar with the subject matter and you are holding a thoughtful discussion to understand another person's opinions. Stay on the moderator-defined topic, challenge inconsistencies respectfully, and keep the dialogue collaborative rather than interrogative. Always dig beneath surface statements and notice strength of sentiment, uncertainty, or indifference. Track nuanced shifts across the entire conversation.\n\nWork through the user's latest response with explicit chain-of-thought reasoning in your private notes before answering. Segment the response into clear bullet points that capture the user's intent, tone, and confidence. Compare each point EXCLUSIVELY against what the user has previously stated in this conversation (as recorded in the Live Notes). Information is considered NEW if the user has not mentioned it before in this conversation, regardless of whether it is common knowledge or widely known. Your role is to track what THIS SPECIFIC USER has shared, not to evaluate whether the information is novel to you or to general knowledge. Use your knowledge ONLY to understand and interpret the user's responses, NOT to determine whether information is new. Request clarifications when vagueness or contradictions appear.\n\nNever mention or expose the chain-of-thought itself when speaking to the user. Keep the tone professional and inquisitive.")),
                ('moderator_system_prompt', models.TextField(blank=True, default="You are an impartial moderator distilling multiple expert perspectives. Read each user views document carefully. Maintain a scratchpad containing your step-by-step reasoning, hypotheses, and cross-user comparisons. After studying every user, review that scratchpad to craft a nuanced, pointwise comparison. Highlight areas of consensus, disagreement, strength of sentiment, confusion, and missing information. Present your analysis as JSON with fields 'moderator_temp' (your reasoning process) and 'summary_md' (final synthesis with keys: consensus, disagreement, strength_of_sentiment, confusion, missing_information). Each key should map to an array of insight strings.")),
                ('user_instructions', models.TextField(blank=True, help_text='Optional moderator-provided instructions for participants')),
                ('knowledge_base', models.TextField(blank=True)),
                ('rag_chunk_count', models.PositiveIntegerField(default=0)),
                ('rag_last_built_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_temp', models.TextField(blank=True)),
                ('moderator_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GraderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=64, unique=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed session description (rendered as markdown)')),
                ('objective_questions', models.JSONField(blank=True, default=list)),
                ('knowledge_base', models.TextField(blank=True)),
                ('rag_chunk_count', models.PositiveIntegerField(default=0)),
                ('rag_last_built_at', models.DateTimeField(blank=True, null=True)),
                ('user_instructions', models.TextField(blank=True, help_text='Optional moderator-provided instructions for graders')),
                ('analysis_markdown', models.TextField(blank=True, help_text='LLM-generated analysis of collected grader feedback')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AIDebateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('objective_questions', models.JSONField(blank=True, default=list)),
                ('personas', models.JSONField(blank=True, default=list)),
                ('summary_markdown', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.aideliberationsession')),
            ],
            options={
                'verbose_name_plural': 'AI Debate Summaries',
            },
        ),
        migrations.CreateModel(
            name='AIDebateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_runs', to='core.aideliberationsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GraderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('scores', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.gradersession')),
            ],
            options={
                'ordering': ('-submitted_at',),
                'constraints': [models.UniqueConstraint(fields=('session', 'user_id'), name='unique_grader_response_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('history', models.JSONField(blank=True, default=list)),
                ('scratchpad', models.TextField(blank=True)),
                ('views_markdown', models.TextField(blank=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('consecutive_no_new', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('question_followups', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.discussionsession')),
            ],
            options={
                'ordering': ('session_id', 'user_id'),
                'constraints': [models.UniqueConstraint(fields=('session', 'user_id'), name='unique_user_per_session')],
            },
        ),
    ]
