"""Add grader integration: grader questions field and DiscussionGraderResponse model.

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionsession",
            name="grader_objective_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="DiscussionGraderResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("user_id", models.PositiveIntegerField()),
                ("scores", models.JSONField(blank=True, default=list)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("additional_comments", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="grader_responses",
                        to="core.discussionsession",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="discussiongraderresponse",
            constraint=models.UniqueConstraint(fields=("session", "user_id"), name="unique_discussion_grader_response_per_user"),
        ),
    ]
