# Generated by Django 4.2.7 on 2025-11-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionsession',
            name='grader_objective_questions',
        ),
        migrations.AddField(
            model_name='userconversation',
            name='responses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='DiscussionGraderResponse',
        ),
    ]
