# Generated by Django 5.1.2 on 2025-10-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discussionsession_delete_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconversation',
            name='cumulative_understanding',
        ),
    ]
