# Generated by Django 4.2.7 on 2025-12-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_discussionsession_grader_objective_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionsession',
            name='concept_cluster_html',
            field=models.TextField(blank=True, help_text='HTML visualization of concept clusters'),
        ),
        migrations.AddField(
            model_name='userconversation',
            name='content_length',
            field=models.PositiveIntegerField(default=0, help_text='Word count of final analysis'),
        ),
        migrations.AddField(
            model_name='userconversation',
            name='termination_reason',
            field=models.CharField(blank=True, help_text='Why conversation ended: manual, followup_limit, no_new_limit, message_limit', max_length=50),
        ),
        migrations.AddField(
            model_name='userconversation',
            name='unique_concepts',
            field=models.JSONField(blank=True, default=list, help_text='List of unique concepts extracted from conversation'),
        ),
    ]
