# Generated by Django 5.1.2 on 2025-10-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userconversation_cumulative_understanding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionsession',
            name='expected_users',
        ),
    ]
