# Generated by Django 5.1.2 on 2025-10-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_discussionsession_expected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionsession',
            name='moderator_system_prompt',
            field=models.TextField(blank=True, default="You are an impartial moderator distilling multiple expert perspectives. Read each user views document carefully. Maintain a scratchpad containing your step-by-step reasoning, hypotheses, and cross-user comparisons. After studying every user, review that scratchpad to craft a nuanced, pointwise comparison. Highlight areas of consensus, disagreement, strength of sentiment, confusion, and missing information. Present your analysis as JSON with fields 'moderator_temp' (your reasoning process) and 'summary_md' (final synthesis with keys: consensus, disagreement, strength_of_sentiment, confusion, missing_information). Each key should map to an array of insight strings."),
        ),
    ]
