# Generated by Django 5.1.2 on 2025-10-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_discussionsession_moderator_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionsession',
            name='objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='discussionsession',
            name='participant_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
