# Generated by Django 5.1.2 on 2025-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_discussionsession_objectives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionsession',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='discussionsession',
            name='participant_count',
        ),
        migrations.AddField(
            model_name='discussionsession',
            name='objective_question',
            field=models.TextField(blank=True),
        ),
    ]
