# Generated by Django 5.1.2 on 2025-10-29

from django.db import migrations, models


def copy_legacy_question(apps, schema_editor):
    DiscussionSession = apps.get_model("core", "DiscussionSession")
    for session in DiscussionSession.objects.all():
        legacy = getattr(session, "objective_question", "") or ""
        cleaned = legacy.strip()
        questions = []
        if cleaned:
            questions.append(cleaned)
        session.objective_questions = questions
        if not session.question_followup_limit:
            session.question_followup_limit = 3
        session.save(update_fields=["objective_questions", "question_followup_limit"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_discussionsession_objectives_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionsession",
            name="objective_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="discussionsession",
            name="question_followup_limit",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="userconversation",
            name="current_question_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userconversation",
            name="question_followups",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(copy_legacy_question, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="discussionsession",
            name="objective_question",
        ),
    ]
