# Generated by Django 5.1.2 on 2025-10-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_multi_question_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionsession",
            name="no_new_information_limit",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
